# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-17 09:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recordApp', '0004_auto_20180917_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('book_id', models.CharField(max_length=20, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('book_type', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=30)),
                ('publish_time', models.DateField()),
                ('publish_house', models.CharField(max_length=30)),
                ('content', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': '\u56fe\u4e66',
            },
        ),
        migrations.CreateModel(
            name='BorrowBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateField(auto_now_add=True)),
                ('return_date', models.DateField()),
                ('price', models.CharField(default='100', max_length=10)),
                ('book_name', models.ManyToManyField(to='libApp.BookInfo')),
                ('stu_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recordApp.StuInfo')),
            ],
            options={
                'verbose_name_plural': '\u501f\u9605\u5355',
            },
        ),
    ]
