# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-17 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stuinfo',
            name='subject',
        ),
        migrations.AddField(
            model_name='stuinfo',
            name='subject',
            field=models.ManyToManyField(to='recordApp.Subject'),
        ),
    ]
