# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-17 08:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recordApp', '0002_auto_20180917_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuinfo',
            name='major',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='recordApp.Major'),
        ),
    ]
