# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-17 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordApp', '0003_stuinfo_major'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='leave_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
